### ISSUE TITLE
Request for requirement.txt

### ISSUE THREAD

**Issue by jinghan23** [qtli/GSM-Plus#2]
Would you mind uploading the environment requirements so that we can create the environment directly? Thanks in advance!

**Comment by qtli** [comment]
Hi! Thanks for your interest. 
I have uploaded the `requirements.txt` for your reference.

**Comment by jinghan23** [comment]
Thanks it solved

**Comment by jinghan23** [comment]
Sorry for reopening but I think there maybe some conflicts.
By the way may I know your python version?
```
ERROR: Cannot install -r requirements.txt (line 25) and transformers==4.18.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested transformers==4.18.0
    vllm 0.3.3 depends on transformers>=4.38.0

**Comment by qtli** [comment]
> 
Hi @jinghan23, I apologize for the delay. The previous server is no longer accessible, so I have re-installed the environment on a new server. The following packages have been installed:
```
vllm==0.2.4+cu118
ray==2.10.0
torch==2.1.2+cu118
tokenizers==0.15.2
transformers==4.39.0
```
I'm currently using Python 3.9.12, but Python 3.10 should also work fine.
